language: objective-c
osx_image: xcode10.3
cache: 
  cocoapods: true
  directories:
    - Carthage

before_install:
  - |
    gem install xcpretty-travis-formatter
    if [ "${PACKAGE_MANAGER}" = "cocoapods" ]; then 
      gem install cocoapods
      pod repo update
      pod update
    else
      brew install carthage || true
      brew outdated carthage || brew upgrade carthage
      carthage update --platform ios --cache-builds
    fi;
script:
- xcodebuild -scheme 'MediaBrowser' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

matrix:
  include:
    - env: PACKAGE_MANAGER=cocoapods
    - env: PACKAGE_MANAGER=carthage
