language: objective-c
osx_image: xcode10.3
cache: cocoapods
before_install:
  - |
    if [ "${PACKAGE_MANAGER}" = "cocoapods" ]; then 
      gem install cocoapods
      pod repo update
      pod update
    else
      brew install carthage || true
      brew outdated carthage || brew upgrade carthage
      carthage update --platform ios --cache-builds
    fi;
script:
- xcodebuild -scheme 'MediaBrowser' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c

matrix:
  include:
    - env: PACKAGE_MANAGER=cocoapods
    - env: PACKAGE_MANAGER=carthage
