language: objective-c
osx_image: xcode10.3
cache: 
  directories:
    - Carthage
    - Pods

addons:
  homebrew:
    packages:
      - carthage
    update: true

before_install:
  - |
    gem install xcpretty-travis-formatter
    if [ "${PACKAGE_MANAGER}" = "cocoapods" ]; then 
      gem install cocoapods
      pod repo update
      pod update
    else
      carthage update --platform ios --cache-builds
    fi;
script:
- xcodebuild -scheme 'MediaBrowser' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

matrix:
  include:
    - env: 
      - PACKAGE_MANAGER=cocoapods
      - ISOLATED=true
    - env: 
      - PACKAGE_MANAGER=carthage
      - ISOLATED=true
